[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
startCommand = "python migrate_postgresql.py && python -m bot.main"
restartPolicyMaxRetries = 5

[[volumes]]
sourcePathSuffix = "data"
mountPath = "/app/data"
